language: ruby
rvm:
- 2.3.1
install:
- "./bin/setup"
script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx --allow-hash-href
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: zhuhaow
  - EMAIL: zhuhaow@gmail.com
  - secure: QdlT9Y80M8fPN1+t9oW5pXOtMclcloWfM3NVd+0tn/cYZ1bHuJLXhEb+YG3QkXLMZ8ROcxFonmnN9ZKawn2NgCoEWMPhYFhYNd0GN07TbPbj3pNYG/+OkEER++kk5b6IpZGW55GAiXJkeMjfwrckmEx2/Hs9Pr1ajd4NnwjgeboBSRbUJzh10R7mqHLt4TtuKC8Yo49WRnUaVEyKalL899KSKJoitu0Uke1ZXlYj+R7LjJno8Hf/EbW9In0ZoZkB5/aJqwVAxwee8F+uNZbGpEaiIwNn8X3mO+c5oQ2ZxE3KVWxoN9GAMP4hDEzS5RI06YaG1O0g4Qc/VYcwD4nv1yiBMe7A/6L6bFr7lIjFEV2WFzg/PMGztZ2r7o6+uRK2l9kysWhBLRkyts4e4RKyGOMXEWKQ5945Wntua+Ndx7KO3xXNKoxp7qdeVTMIQvIRI7JAtProH3wgmLWO92ac0uelCME2/G3MUhg//H7uIwEaG3FGvlb4okTvpz/NyA/n0CfadHIQLjopzvR4JC9CkX6HknMHZYruSRWTUV7YrHX6XCh4su7xefHaemvmoscdN5LxNqF5v7qxg/DSu20F8Hi5bFkMpteDMV5piNFmzr946dIcR52n4FtLtPs5hHYZe0OrqX/u+mGufr1YQbqlHPX2cNQGkrkv//q5WvClnAc=
